name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore PrintAssistantSolution.sln

      - name: Build
        run: dotnet build PrintAssistantSolution.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test PrintAssistantSolution.sln --configuration Release --no-build --collect:"XPlat Code Coverage"

      - name: Upload coverage report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: **/coverage.cobertura.xml

